config/routes.rb
Pricerr::Application.routes.draw do
  

  

  
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  get "users/show"

  devise_for :users

  get "home/index"

  root to: "jobs#index"

  resources :jobs, only: [:new, :create, :index, :show]

  resources :conversations, only: :index do
    resources :messages
  end

  resources :messages, :only => [:new, :create]

  resources :my_jobs, only: :index
  resources :purchase_jobs, only: :index

  resources :requests, only: [:index, :create]
  resources :users, only: [:show, :index] do 
    resources :requests, only: [:new, :create, :show]
    resource :payment, only: :show
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_filter :authenticate_user!

	def index
    if params.key?(:mailbox) && ['inbox', 'sentbox', 'trash'].include?(params[:mailbox])
      @conversations = current_user.mailbox.send(params[:mailbox])
      @active = "#{params[:mailbox]}_active"
    else
      @conversations = current_user.mailbox.inbox
      @active = :inbox_active
    end
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<% content_for @active.to_sym do %>
  active  
<% end %>

<% @conversations.each do |conversation| %>
	<div class="row-fluid">
    <div class="span1 text-center">
		  <%= conversation.receipts.first.message.sender %>:  
    </div>
    <div class="span8">
      <%= link_to conversation.subject, conversation_messages_path(conversation) %>
    </div>
    <div class="span3">
      <%= conversation.last_message.created_at %>
    </div>
	</div>
  <hr/>
<% end %>