config/routes.rb
Pricerr::Application.routes.draw do
  

  

  
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  get "users/show"

  devise_for :users

  get "home/index"

  root to: "jobs#index"

  resources :jobs, only: [:new, :create, :index, :show]

  resources :conversations, only: :index do
    resources :messages
  end

  resources :messages, :only => [:new, :create]

  resources :my_jobs, only: :index
  resources :purchase_jobs, only: :index

  resources :requests, only: [:index, :create]
  resources :users, only: [:show, :index] do 
    resources :requests, only: [:new, :create, :show]
    resource :payment, only: :show
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :description, :title, :user_id, :price, :category_id, :location_id, :days
  attr_accessible :tag_list, :images_attributes, :extra_jobs_attributes

  belongs_to :user
  belongs_to :category
  belongs_to :location

  has_many :images, dependent: :destroy
  has_many :extra_jobs, dependent: :destroy
  has_many :purchase_jobs, dependent: :destroy

  validates_presence_of :user, :description, :title, :price, :category, :days
  validates_numericality_of :price, :days

  accepts_nested_attributes_for :images, :reject_if => :all_blank
  accepts_nested_attributes_for :extra_jobs, :reject_if => proc { |a| a[:description].blank? || a[:price].blank? }
  
  acts_as_taggable

  scope :recent, order('created_at desc')

  scope :find_by_title_or_description, lambda {|word| where("title ilike ? OR description ilike ?", "%#{word}%", "%#{word}%")}

  self.per_page = 10


  def full_title
    "I will #{title} for #{ActionController::Base.helpers.number_to_currency(price)}"
  end

  class << self

    def get_from_params (params)

      ### MAYBE CAN CHANGE THIS LOGIC TO A PRESENTER
      if params.key?(:category) 
        key = :category 
        filter_title = "All #{params[key]} Jobs"
        jobs = find_jobs_from_class(key, params[key])
      elsif params.key?(:location) 
        key = :location
        filter_title = "All Jobs in #{params[key]}"
        jobs = find_jobs_from_class(key, params[key])
      elsif params.key?(:user_id)
        user = User.includes(:jobs).find(params[:user_id])
        jobs = user.jobs
        filter_title = "All #{user.name} Jobs"
      elsif params.key?(:tag)
        jobs = Job.includes(:category).tagged_with(params[:tag])
        filter_title = "All Jobs with tag: #{params[:tag]} "
      elsif params.key?(:q)
        jobs = find_by_title_or_description(params[:q])
        filter_title = "Jobs"
      else
        jobs = includes(:category)
        filter_title = "All Posted Jobs"
      end
      [jobs, filter_title]
    end

    def find_jobs_from_class(key, value)
      klass = key.to_s.capitalize.constantize
      klass.includes(:jobs).find_by_name(value).jobs
    end

  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    respond_to do |format|
      format.html do
        @jobs, @jobs_filter_title = Job.get_from_params(params)
        @jobs = @jobs.recent.paginate(page: params[:page])
      end

      format.json do
        @jobs = Job.find_by_title_or_description(params[:q]).recent.limit(5)
        render json: @jobs.to_json(only: [:title, :price, :id, :description])
      end
    end
  end


  def show
    @job = Job.includes(:images, :extra_jobs).find(params[:id])
    @tags = @job.tags
    @images = @job.images.recent
    @extra_jobs = @job.extra_jobs.recent
    unless @images.empty?
      @first_image = @images.first
      @other_images = @images[1..-1]
    end
  end

  def new
    @title = params[:title] || ''
    @price = params[:price] || ''
    @job = current_user.jobs.new
    4.times { @job.images.build }
    10.times { @job.extra_jobs.build }
  end

  def create
    @job = current_user.jobs.new(params[:job])
    if @job.save
      redirect_to(root_path, notice: 'Job was succesfully created.')
    else
      (4 - @job.images.size).times{ @job.images.build }
      render action: 'new'
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.erb
<div class="row-fluid">
  <div class="span2">
    <%  unless job.images.empty? %>
      <%= image_tag job.images.recent.first.image_url(:small_thumb) %>
    <% else %>
      <img data-src="holder.js/100x100" alt="">
    <% end %>
  </div>
  <div class="span10">
    <h4><%= link_to job.full_title, job %></h1>
    <p><%= "#{truncate(job.description, length: 70)} by ( #{job.user.name} )"  %></p>
    <p><%= job.category %></p>
  </div>
</div>
<hr class="soften"/> 

app/views/jobs/index.html.erb
<div class="container-fluid">
<!--     <%= form_tag :new_job, method: :get do %>
    <div class="row-fluid">
      <div class="span5">
        <div class="span2">I will</div>
        <div class="span10"><%= text_field_tag :title, nil, :class => 'span12' %></div>
      </div>
      <div class="span2">
        <div class="span4">for $</div>
        <div class="span6"><%= text_field_tag :price, nil, :class => 'span12' %></div>
      </div>
      <div class="span2"><%= button_tag "Continue", :class => 'btn btn-info' %></div>
    </div>
    <% end %> -->
    <div class="row-fluid">
      <%= form_tag :new_job, method: :get, :class => 'form-inline' do %>
          <%= label_tag :title, 'I will' %> 
          <%= text_field_tag :title, nil, :class => 'input-xlarge' %>
          <%= label_tag :price, 'for' %>
          <div class="input-prepend">
            <span class="add-on">$</span>
            <%= text_field_tag :price, nil, :class => 'input-mini' %>
          </div>
          
        <%= button_tag "Continue", :class => 'btn btn-info' %>
      
      <% end %>
    </div>

  <h3><%= @jobs_filter_title %></h3>
  <%= render @jobs %>
  <%= will_paginate @jobs, :renderer => BootstrapPagination::Rails %>
</div>

app/views/jobs/new.html.erb
<%= form_for @job, :html => {:multipart => true} do |f| %>
  <% @messages = @job.errors.messages %>
  <div class="row-fluid">
    <div class="span2"><%= f.label :title, 'I will:' %></div>
    <div class="span6">
      <div class="span8">
        <%= f.text_field :title, value: @title, :class => 'span11' %>
        <% unless @messages[:title].empty? %>
          <div class="control-group error"><span class="help-inline"><%= @messages[:title].first %></span></div>
        <% end %>
      </div>
      <div class="span2"><%= f.label :price, 'for $' %></div>
      <div class="span2">
        <%= f.text_field :price, value: @price, :class => 'span12' %>
        <% unless @messages[:price].empty? %>
          <div class="control-group error"><span class="help-inline"><%= @messages[:price].first %></span></div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span2"><%= f.label :description, 'Description:' %></div>
    <div class="span6">
      <div class="span12">
        <%= f.text_area :description, :class => 'span12', size:'1x5'%>
      </div>
    </div>
    <div class="span4">
      <% unless @messages[:description].empty? %>
        <div class="control-group error"><span class="help-inline"><%= @messages[:description].first %></span></div>
      <% end %>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span2"><%= f.label :category_id, 'Category:' %></div>
    <div class="span6">
      <div class="span12">
        <%= collection_select(:job, :category_id, Category.all, :id, :name) %>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span2"><%= f.label :location_id, 'Location:' %></div>
    <div class="span6">
      <div class="span12">
        <%= collection_select(:job, :location_id, Location.all, :id, :name) %>
      </div>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span2"><%= f.label :tag_list, 'Tags:' %></div>
    <div class="span6">
      <div class="span12">
        <%= f.text_field :tag_list, :class => 'span5', placeholder: 'separate your tags by comma' %>
      </div>
    </div>
  </div>


  <div class="row-fluid">
    <div class="span2"><%= f.label :days, 'Max Days to Deliver:' %></div>
    <div class="span6">
      <div class="span12">
        <%= f.text_field :days, :class => 'span4' %>
      </div>
    </div>
    <div class="span4">
        <% unless @messages[:days].empty? %>
          <div class="control-group error"><span class="help-inline"><%= @messages[:days].first %></span></div>
        <% end %>      
    </div>
  </div>



  <div class="row-fluid">
    <div class="span2">Image:</div>
    <div class="span6">
      <div class="span12">
        <%= f.fields_for :images do |ff|%>
          <%= ff.file_field :image %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="row-fluid">
    <div class="span8 well">
      <%= f.fields_for :extra_jobs do |ff| %>
      <div class="row-fluid">
        <div class="span4 form-inline">
          <%= ff.label :price, 'For an extra' %> 
          <div class="input-prepend">
            <span class="add-on">$</span>
            <%= ff.text_field :price, :class => 'input-mini' %>
          </div>
        </div>
        <div class="span8 form-inline">
          <%= ff.label :description,'I will:' %> <%= ff.text_field :description, :class => 'input-large' %>
        </div>
      </div>
      <% end %>
    </div>
  </div>



  <div class="row-fluid">
    <div class="span6 offset2">
      <%= f.button :class => 'btn btn-primary'  %>
    </div>
  </div>
  
<% end %>

app/views/jobs/show.html.erb
<div class="row-fluid show-header">
  <h1><%= link_to @job.user.name, user_path(@job.user)%>: <%= @job.full_title %></h1>
</div>
<div class="row-fluid spec-list">
  <div class="span2">JOB RATING</div>
  <div class="span3">DELIVERY IN: <%= pluralize @job.days, 'day' %></div>
  <div class="span2">ORDERS IN QUEUE</div>
  <div class="span2">SELLER RATING</div>
  <div class="span2">VIEWS</div>
</div>

<div class="row-fluid">
  <div class="span4" id="gallery" data-toggle="modal-gallery" data-target="#modal-gallery">
    <div class="row-fluid">
      <ul class="thumbnails">
        <li class="span12">
          
            <% if defined? @first_image %>
              <a href="<%= @first_image.image_url %>" class="thumbnail" data-gallery="gallery">
                <%= image_tag @first_image.image_url(:thumb) %>
            <% else %>
              <a href="#" class="thumbnail">
                <img data-src="holder.js/300x300" alt="">
            <% end %>
            </a>
        
        </li>
      </ul>
    </div>
    <div class="row-fluid">
      <ul class="thumbnails">
        <% if defined? @other_images %>
          <% @other_images.each do |picture| %>
            <li class="span4"><a href="<%= picture.image_url %>" class="thumbnail" data-gallery="gallery"><%= image_tag picture.image_url(:small_thumb) %></a></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="span8">
    <div class="row-fluid desc-paragraph">
      <%= @job.description %>
    </div>
    <div class="row-fluid desc-paragraph">
      Tags: <% @tags.each do |tag| %>
        <%= link_to tag.name, jobs_path(tag: tag.name), :class => "btn btn-inverse btn-mini" %> 
      <% end %>
    </div>
    <div class="row-fluid">
      <div id="socialButtons" class="span12">
      </div>
    </div>
  </div>
</div>

<% unless @extra_jobs.empty? %>
<div class="row-fluid ">
  <div class="span8 well">
    <h3>Get more with my extra Jobs</h3>
    <% @extra_jobs.each do |extra_job| %>
      <div class="row-fluid inverted">
        <div class="span10">
          <%= check_box_tag(:extra_job) %> I will <%= extra_job.description %>
        </div>
        <div class="span2">
          + <%= number_to_currency(extra_job.price) %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% end %>

<div id="modal-gallery" class="modal modal-gallery hide fade" tabindex="-1">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3 class="modal-title"></h3>
  </div>
  <div class="modal-body"><div class="modal-image"></div></div>
  <div class="modal-footer">
    <a class="btn btn-info modal-prev"><i class="icon-arrow-left icon-white"></i> Previous</a>
    <a class="btn btn-primary modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
    <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Slideshow</a>
    <a class="btn modal-download" target="_blank"><i class="icon-download"></i> Download</a>
  </div>
</div>