config/routes.rb
Pricerr::Application.routes.draw do
  

  

  
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  

  get "users/show"

  devise_for :users

  get "home/index"

  root to: "jobs#index"

  resources :jobs, only: [:new, :create, :index, :show]

  resources :conversations, only: :index do
    resources :messages
  end

  resources :messages, :only => [:new, :create]

  resources :my_jobs, only: :index
  resources :purchase_jobs, only: :index

  resources :requests, only: [:index, :create]
  resources :users, only: [:show, :index] do 
    resources :requests, only: [:new, :create, :show]
    resource :payment, only: :show
  end

end

app/controllers/my_jobs_controller.rb
class MyJobsController < ApplicationController
  before_filter :authenticate_user!
  def index
    if ['active', 'finished', 'unreviewed'].include?(params[:status])
      @jobs = current_user.send("#{params[:status]}_jobs")
      @title =  (params[:status] == 'unreviewed' ? 'In Review' : "#{params[:status].camelize}") + " Jobs"
    else
      @jobs = current_user.active_jobs
      @title = 'Active Jobs'
    end
  end
end

app/helpers/my_jobs_helper.rb
module MyJobsHelper
end

app/views/my_jobs/_job.html.erb
<tr id="<%= dom_id job %>">
  <td><%= link_to "I will #{job.title}", job_path(job.job) %></td>
  <td><%= job.buyer %></td>
  <td><%= job.deliver_date %></td>
  <% if title == 'Finished Jobs' %>
    <td><%= job.review %></td>
  <% end %>
</tr>

app/views/my_jobs/index.html.erb
<%= render 'shared/accounts/sidebar' %>

<h3><%= @title %></h3>

<div class="row-fluid pattern1">
  <div class="span12 well">
    <div class="span2 subpattern1" id="active_jobs"><%= link_to "Active", my_jobs_path(status: :active) %>: <%= current_user.active_jobs.count %></div>
    <div class="span2 subpattern1" id="finished_jobs"><%= link_to "Finished", my_jobs_path(status: :finished) %>: <%= current_user.finished_jobs.count %></div>
    <div class="span2" id="unreviewed_jobs"><%= link_to "In Review", my_jobs_path(status: :unreviewed) %>: <%= current_user.unreviewed_jobs.count %></div>
  </div>
</div>

<br/>

<div class="span10">
  <table class="table table-bordered">
    <thead>
      <th>Title</th>
      <th>Customer</th>
      <th>Delivery Date</th>
      <% if @title == 'Finished Jobs' %>
        <th>Review</th>
      <% end %>
    </thead>
    <tbody>
      <%= render partial: 'job', collection: @jobs, locals: {title: @title} %>
    </tbody>
  </table>
</div>